datasources:
    -  access: 'proxy'
       editable: true
       is_default: true
       name: 'InfluxDB'
       org_id: 1
       type: 'influxdb'
       url: 'http://influxdb-datasource:8086'
       database: 'dom'
       version: 1