---
- name: DOM details for setup
  hosts: dom
  connection: network_cli
  gather_facts: no

  tasks:
    - name: run detail commands
      ios_command:
        commands:
          - show interfaces transceiver detail
          - show interfaces transceiver properties